### ISSUE TITLE
cfg dir

### ISSUE THREAD

**Issue by ccsimplyspolit** [BeepIsla/valve-region-selector#1]
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\Users\ccsim\Desktop\operation-missions-master\operation-missions-master\cfg'

**Comment by BeepIsla** [comment]
Did you post this issue in the wrong repository?

**Comment by ccsimplyspolit** [comment]
oh, ye, wrong repo operation-missions-master.

**Comment by BeepIsla** [comment]
Just create a folder called `cfg` and it should fix it. That's it. I also pushed out a fix for this so it shouldn't happen again when you redownload.

Marked as invalid because of wrong repo.
