### ISSUE TITLE
steam exe dont open and still say waiting

### ISSUE THREAD

**Issue by tomer6400** [BeepIsla/valve-region-selector#12]
steam exe dont open and still say waiting

**Comment by BeepIsla** [comment]
You should be able to just make a Steam shortcut and use the extra parameters `-websocket -websocketignorecertissues` and manually launch Steam

**Comment by tomer6400** [comment]
When i try to open it is type starting the steam start to open and after this its just closed and the status come back to waiting

**Comment by tomer6400** [comment]
If you can explain yourself I would be happy

**Comment by BeepIsla** [comment]
I don't know what the problem is.

**Comment by tomer6400** [comment]
Do you have a discord? I'll send you video of the problem that way you might understand better

**Comment by BeepIsla** [comment]
I do not give out my Discord. You told me what the issue is, I told you everything I know, there is nothing more I can do.
