### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by mocnidit** [BeepIsla/valve-region-selector#14]
Ok, I live in South Africa and since there aren't many players, I've decided to get this app. It is working, and thank you for that, but there is a problem that I believe you can fix. How should I modify regions, specifically pings, because I when I try to that by myself, my game is always on 200-300 ping while normally it is 40. Thank you for your attention and your answer.

**Comment by BeepIsla** [comment]
The further away the server you are playing on is the higher your ping. Long Distance = High Ping. Not fixable.
