### ISSUE TITLE
New Regions

### ISSUE THREAD

**Issue by mouselifter** [BeepIsla/valve-region-selector#15]
Valve has added new regions in Argentina & Bulgaria

Possible to add these? Thank you and bless you.

**Comment by BeepIsla** [comment]
The program automatically fetches the latest SDR configuration from here (https://api.steampowered.com/ISteamApps/GetSDRConfig/v1/?appid=730) every time you start it. After the update I checked and couldn't find Argentina in that configuration file, it may be under a different name or simply not included.

I will check again and verify later to see if I can find it, if not then I don't quite know what to do.

**Comment by BeepIsla** [comment]
Try changing your ping to `Santiago` to access Argentina servers.
