### ISSUE TITLE
JavaScript error when turning on.

### ISSUE THREAD

**Issue by ghost** [BeepIsla/valve-region-selector#19]
After clicking the enable button and selecting my steam.exe I am presented with [this](https://i.imgur.com/7OQ96nB.png) error.
Dismissing the error just leaves the Status as "starting".

I have attempted running the program in administrator, having steam closed prior to running the program and selecting a shortcut for steam, however none have fixed the issue.

**Comment by BeepIsla** [comment]
I have no idea what the cause of this could be

**Comment by ghost** [comment]
Ok so deleting everything in AppData/Roaming/region-selector (or whatever its folder is), uninstall and reinstalling it, running it, and then while it says starting, running a shortcut to steam with the -websocket -websocketignorecertissues launch params, has left me stuck at "Connecting Steam account: alias..."

**Comment by ghost** [comment]
I guess that was just a one time thing, following steps above it is working again :D
