### ISSUE TITLE
Save config/preset

### ISSUE THREAD

**Issue by 45656456kawai** [BeepIsla/valve-region-selector#2]
Title ^

Would be nice to have that : ) Thank you.

**Comment by BeepIsla** [comment]
I was working on that for a short bit, the current development version has a very basic implementation of this as in:
- Automatically saves every time you modify the settings
- Automatically loads the last used settings every time the program starts

I assume you would want a tab for loading, saving and deleting configs?

**Comment by 45656456kawai** [comment]
Yeah, a tab would be nice. However, the automatically saves/loads don't work for me it resets every time the app closes.

**Comment by BeepIsla** [comment]
> However, the automatically saves/loads don't work for me it resets every time the app closes.

Its only in the latest development version, if you downloaded from the release section of Github you will not have this feature.

If you downloaded the source code and compiled it yourself then it should work.

**Comment by 45656456kawai** [comment]
Ahh well, unfortunately, IDK how to compile it :/ Btw having a button for select/tick/untick all would be nice.

**Comment by BeepIsla** [comment]
> Ahh well, unfortunately, IDK how to compile it

That's fine, I am already working on it, might release a new version it later today/tomorrow.

> Having a button for select/tick/untick all would be nice.

I agree, I will try and add this without taking up too much space.

**Comment by BeepIsla** [comment]
Both has been added in [Version 1.2.0](../releases/tag/1.2.0). Try it out and close if it works.

**Comment by 45656456kawai** [comment]
Works, thank you.
