### ISSUE TITLE
How do I revert back to normal?

### ISSUE THREAD

**Issue by hondazo** [BeepIsla/valve-region-selector#20]
![20210417175220_1](https://user-images.githubusercontent.com/73078353/115122353-bdf95e00-9fb7-11eb-9503-f7792f126415.jpg) 

This keeps on popping up.

**Comment by BeepIsla** [comment]
Just run Steam like normal, CSGO will send ping updates every few minutes.

**Comment by hondazo** [comment]
That didn't work. Is there any other way to fix?

**Comment by BeepIsla** [comment]
There is not. Increase your max ping in the game settings either CSGO servers or your internet are having issues.

The way this program works is it basically sits between the Steam Servers and CSGO. When CSGO sends ping data the program modifies it. If Steam isn't started with the program nothing will modify the ping data and just the original will be used.

**Comment by hondazo** [comment]
Just in case you're wondering what error I'm getting.
[#1795894957 SDR server steamid:90145588856229897 vport 0] problem detected locally (5003): Timeout. Some relay connectivity but primary not perfect.  Cause unknown.
Steam Net connection #1795894957 SDR server steamid:90145588856229897 vport 0 problem detected locally, reason 5003: Timeout. Some relay connectivity but primary not perfect.  Cause unknown.

**Comment by hondazo** [comment]
It's my ISP

**Comment by BeepIsla** [comment]
Yeah nothing to do with this program, it doesn't touch any of that and you said its your ISP. I don't know how to resolve that so that is on you now.
