### ISSUE TITLE
No servers show up

### ISSUE THREAD

**Issue by isoche16** [BeepIsla/valve-region-selector#25]
Hi, the app has been working fine till today, works fine on my friends but not for me anymore..i resetted my modem,router,internet and reinstalled but still same, firewall off. antivirus off
![Screenshot_201](https://user-images.githubusercontent.com/86754932/124053488-04901d80-da29-11eb-9c7f-37b79ca88345.png)

**Comment by isoche16** [comment]
+I fixed the problem by activating the Proxy servers on Network Settings/Lan Settings

**Comment by BeepIsla** [comment]
Weird, but good it is now fixed.
