### ISSUE TITLE
Saying still waiting after choosing Steam.exe

### ISSUE THREAD

**Issue by Ijustcreatedthisaccounttoaskaquestion** [BeepIsla/valve-region-selector#26]
I know this question is asked before but It hasn't been answered 
I am choosing the steam.exe file in C:\Program Files (x86)\Steam but It says Starting then goes and says Waiting 
Here's a YouTube video Explaining the issue: 
https://www.youtube.com/watch?v=M2zwesjgeAc

(Damn this will take at least a month to get a respond from the devs)

**Comment by BeepIsla** [comment]
I do not actively maintain this project, it is open source for possible pull requests. As for your issue: Seems like Steam crashes for some reason, it gets hard to debug issues like this. The only thing I can ask is: Are you using Steam Beta or Steam Stable? (Steam -> Settings -> Account -> Beta Participation) Try switching it around, maybe that helps?

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
https://imgur.com/a/6hq40LS
https://imgur.com/a/j1t6Vsb
I tried installing older versions and It does the same thing, I think this application got patched That's all I can think of...
It really doesn't make any sense at all damn it! I really wanted to try out that custom ping :(
(I wasn't signed up for steam beta participation but I went ahead and tried joining it and It still says waiting after selecting the Steam.exe)

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
I am the most unluckiest guy ever It has to be fixed whenever I try something out

**Comment by BeepIsla** [comment]
The only way Valve could patch it is by removing Steam launch options that the use themselves and even then I could just change it to use another system anyways. All in all: It seems unpatchable without major rewrites for no profit on Steam's end. I just tried it myself and Steam starts fine.

So either you can give up or you can try and get more info on this by follow these steps:

1. Install [NodeJS v16](https://nodejs.org/en/)
2. Download this repository and extract the zip
3. Open a command prompt inside the folder where you extracted all the content
4. Run `npm ci`
5. Wait until all dependencies have been installed
6. Run `npm start`

This should then open the program like normal except you have an additional command prompt open with possibly more debug information logged.

For example this is how it looks for me when it works fine:
```
D:\JavaScript\valvegames-region-selector>npm start

> valvegames-region-selector@1.4.0 start
> electron .


(node:1544) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Best ping to cm is 52 on cm1-fra1.cm.steampowered.com:27032
```

You can ignore the `DeprecationWarning` message. Maybe this has more information as to why Steam crashes, maybe not. There isn't a lot of logging information in this program.

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
```
(node:1248) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: connect EACCES 146.66.155.54:27038
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27038
}
Error: connect EACCES 146.66.155.38:27031
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27031
}
Error: connect EACCES 146.66.155.54:27029
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27029
}
Error: connect EACCES 146.66.155.54:27034
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27034
}
Error: connect EACCES 146.66.155.38:27029
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27029
}
Error: connect EACCES 146.66.155.38:27037
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27037
}
Error: connect EACCES 146.66.155.38:27035
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27035
}
Error: connect EACCES 146.66.155.38:27028
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27028
}
Error: connect EACCES 146.66.155.54:27028
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27028
}
Error: connect EACCES 146.66.155.38:27038
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27038
}
Error: connect EACCES 146.66.155.54:27033
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27033
}
Error: connect EACCES 146.66.155.38:27039
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27039
}
Error: connect EACCES 146.66.155.54:27036
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27036
}
Error: connect EACCES 146.66.155.54:27039
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27039
}
Error: connect EACCES 146.66.155.38:27033
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27033
}
Error: connect EACCES 146.66.155.54:27032
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27032
}
Error: connect EACCES 146.66.155.38:27030
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27030
}
Error: connect EACCES 146.66.155.38:27032
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27032
}
Error: connect EACCES 146.66.155.38:27034
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.38',
  port: 27034
}
Error: connect EACCES 146.66.155.54:27031
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'connect',
  address: '146.66.155.54',
  port: 27031
}
Error: All connection managers have failed to ping
    at Request._callback (C:\Users\kbtca\Desktop\valve-region-selector-master\components\Steam.js:157:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Steam exited with code: null, signal: SIGKILL
```
I'll act as I understand all of this but I think It can't connected to Valve?

**Comment by BeepIsla** [comment]
As far as I can tell it seems to be related to firewall settings, something blocking the program from connecting to Steam servers

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
![image_2021-08-11_063325](https://user-images.githubusercontent.com/88747600/128943457-cb989945-748c-4f8e-b7e9-19ee8fef00c7.png)
Well, I did this...  (It haven't worked doe)
but good news! I tried disabling my firewall and It worked!
but I'll have to disable my firewall everytime I want to play CS:GO which I will feel kinda unsecuried but I think there is no way else around...

**Comment by BeepIsla** [comment]
Try allowing all inbound *and* outbound traffic from the application.

Alternatively you could also maybe try going into your "Control Panel -> System and Security -> Windows Defender Firewall -> Allowed Applications" and select Valve Region Selector there and give it permission. I don't know if what I described and what you have shown do the same thing or not but I guess it can't harm?

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
I actually did what you've said in that picture, give the application inbound and outbound permission but haven't worked but when I tried disabling my firewall and It worked 
also I tried what you've said as an alternative and It didn't work as well

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
imma play on antarctica now 😎

**Comment by BeepIsla** [comment]
That is very weird. Maybe you have a duplicate entry for the program somewhere?

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
![Capture](https://user-images.githubusercontent.com/88747600/128944638-a8775021-6209-4856-959f-f05ec9902043.PNG)
I think I got whatcha said
tried enabling them but doesn't work dammit

**Comment by BeepIsla** [comment]
Maybe deleting all of the entries except one works?

**Comment by Ijustcreatedthisaccounttoaskaquestion** [comment]
It didn't I did exactly what you've said
I mean playing without my firewall on could work for me 
I mean I have no friends I can try being friends with a hacker trying to ddos me while my firewall is off idk
thanks for the help 
![image_2021-08-11_065515](https://user-images.githubusercontent.com/88747600/128945102-ee302147-4773-411f-91f8-fc561a75ad43.png)

**Comment by BeepIsla** [comment]
Good it works now, weird you have to turn off your firewall entirely for it to work. I don't know why this happens. Enjoy playing.
