### ISSUE TITLE
Question about running steam

### ISSUE THREAD

**Issue by kura6789** [BeepIsla/valve-region-selector#3]
I'm using this command to run steam (in .bat file ofc):
cd "C:\Program Files (x86)\Steam"
start steam.exe -applaunch 730  -novid  -console -login login pass

(Faster login and many other reasons)
Is it possible to run it with this program?
Thank you in advance

**Comment by BeepIsla** [comment]
Start steam with the bat, then click `Enable` on the program. It will close Steam and automatically start it again with **the same** launch parameters plus the required ones (At least in theory I don't know if I tested this or not).

**Comment by kura6789** [comment]
Hmm its working but... im running multiple accs in the same time and then its not working. Is there any way to set it permamently? I mean always run steam with choosen servers without clicking enable? I think it will work :D

**Comment by BeepIsla** [comment]
Thats not possible with this program. It overall doesn't support multiple Steam Instances, its way too complicated to implemented, possible but I am not going to do that.

The only way you could accomplish something like that is writing your own entire Steam Proxy basically and routing all Steam traffic through that on local server and change pings accordingly. Still complicated but much easier to do if you want to make your own thing, I am not going to do such a thing.

**Comment by kura6789** [comment]
Hmm yes... but i think I got 2 likely solutions:
1. run valve-region-selector in each instance (testing but have this error when trying to select steam.exe)
![1](https://user-images.githubusercontent.com/28402838/75390517-aa3cf500-58e8-11ea-9f55-ec9e073d2bed.jpg)
Translation: 
The default application setting has been reset
The application caused a problem with the default settings for .jpg files, so they have been reset to: photo

2. run valve-region-selector once and join all accs to same lobby, then "valve mm searcher" is going to search mm in same area as picked in selector (am I right?)

**Comment by BeepIsla** [comment]
This program isn't really usable for the situation you want to use it in. You likely have to find another solution or create your own.
