### ISSUE TITLE
Name of Region "can"

### ISSUE THREAD

**Issue by iebb** [BeepIsla/valve-region-selector#5]
Currently living in the city, and the city is actually named Guangzhou (also historically romanized as Canton).

"Guangzhou Baiyun" is the name of the CAN airport, and Baiyun literally means "white cloud" in Chinese, referring to the nearby Baiyunshan (lit. "white cloud mountain")

https://github.com/BeepIsla/valve-region-selector/blob/f2bf1f423a31c4fda05238b5fb36c21bd069314a/public/js/index.js#L32

**Comment by BeepIsla** [comment]
So just to make sure the actual name is `Guangzhou` and not `Guangzhou Baiyun`?

**Comment by iebb** [comment]
Yeah, you can check it here: https://en.wikipedia.org/wiki/Guangzhou

**Comment by BeepIsla** [comment]
Thanks! I have fixed this now (4b58478e1c300d40ddf96f34bc3574f44697347d). It will be included in the next version, no ETA for release.
